//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDGIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_HaveInTheWindList
    {
        public int HaveInTheWindID { get; set; }
        public Nullable<int> SickpersonID { get; set; }
        public Nullable<int> DiseaseregistrationID { get; set; }
        public string TracedArea { get; set; }
        public string TrackingUnit { get; set; }
        public string TrackingSituation { get; set; }
        public string TracingMethod { get; set; }
        public Nullable<System.DateTime> TimeInPlace { get; set; }
        public string InPlaceMethod { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public string TrackingRemarks { get; set; }
        public string MedicalRecordDiagnosis { get; set; }
        public string ReportArea { get; set; }
        public string ReportUnitName { get; set; }
        public string AdmissionUnit { get; set; }
        public string Registration { get; set; }
    }
}
