//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDGIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SickpersonRajectoryrList
    {
        public int SickpersonRajectoryrID { get; set; }
        public Nullable<int> SickpersonDetailID { get; set; }
        public Nullable<decimal> SmX { get; set; }
        public Nullable<decimal> SmY { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
    }
}
