//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GenePoolList
    {
        public int GenePoolID { get; set; }
        public string SickpersonID { get; set; }
        public string SampleNumber { get; set; }
        public string OutpatientNumber { get; set; }
        public string SNPsite { get; set; }
        public string MutableGene { get; set; }
        public string Colorposition { get; set; }
    }
}
