//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_MedicalrecordList
    {
        public int MedicalrecordID { get; set; }
        public Nullable<int> SickpersonID { get; set; }
        public Nullable<int> DiseaseregistrationID { get; set; }
        public Nullable<System.DateTime> DateFirst { get; set; }
        public Nullable<System.DateTime> DiagnosisResult { get; set; }
        public string DiagnosticClassification { get; set; }
        public string DiagnosticResults { get; set; }
        public Nullable<bool> IsItSevere { get; set; }
        public string DrugResistance { get; set; }
        public string SupervisoryUnit { get; set; }
        public string StopReason { get; set; }
        public string QuiescentTime { get; set; }
        public string Nation { get; set; }
        public string Occupation { get; set; }
        public string CensusAddressInter { get; set; }
        public string CensusAddDetail { get; set; }
        public string PatientSource { get; set; }
        public Nullable<System.DateTime> NowSymptomDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> RegistrationTypeID { get; set; }
        public Nullable<int> TreatTypeID { get; set; }
        public Nullable<int> MedicalStatusID { get; set; }
    }
}
