//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SickpersonList
    {
        public int SickpersonID { get; set; }
        public string Cardnumber { get; set; }
        public string name { get; set; }
        public Nullable<int> sexID { get; set; }
        public string Age { get; set; }
        public Nullable<int> cantonID { get; set; }
        public Nullable<int> CrowdclassificationID { get; set; }
        public Nullable<int> CaseClassID { get; set; }
        public Nullable<int> DiseaseTypeID { get; set; }
        public Nullable<int> AuditStatusID { get; set; }
        public Nullable<System.DateTime> DiagnoseDate { get; set; }
        public string CensusAddDetail { get; set; }
        public string IDnumber { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string workunit { get; set; }
        public string Addressnationalstandard { get; set; }
        public string Detailedaddress { get; set; }
        public string Occupation { get; set; }
        public string CensusAddressInter { get; set; }
        public Nullable<System.DateTime> MorbidityDate { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DiseaseID { get; set; }
    }
}
