//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_UsernameList
    {
        public int usernameID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string IDnumber { get; set; }
        public string location { get; set; }
        public string phonenumber { get; set; }
        public string postbox { get; set; }
        public string remarks { get; set; }
        public string UniformAuthenticationCode { get; set; }
        public Nullable<int> UserroleID { get; set; }
        public Nullable<int> BaseDetailID { get; set; }
        public Nullable<int> DepartmenttypeID { get; set; }
        public bool USERReviewNo { get; set; }
    }
}
