//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChronicGeographicInformationSystemEntities : DbContext
    {
        public ChronicGeographicInformationSystemEntities()
            : base("name=ChronicGeographicInformationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_AuthorityList> B_AuthorityList { get; set; }
        public virtual DbSet<B_BaseDetailList> B_BaseDetailList { get; set; }
        public virtual DbSet<B_BaseTypeList> B_BaseTypeList { get; set; }
        public virtual DbSet<B_DiseaseDetailList> B_DiseaseDetailList { get; set; }
        public virtual DbSet<B_DrugfastList> B_DrugfastList { get; set; }
        public virtual DbSet<B_GenePoolList> B_GenePoolList { get; set; }
        public virtual DbSet<B_HaveInTheWindList> B_HaveInTheWindList { get; set; }
        public virtual DbSet<B_MedicalrecordList> B_MedicalrecordList { get; set; }
        public virtual DbSet<B_RoleAuthorityList> B_RoleAuthorityList { get; set; }
        public virtual DbSet<B_SickpersonDetailList> B_SickpersonDetailList { get; set; }
        public virtual DbSet<B_SickpersonList> B_SickpersonList { get; set; }
        public virtual DbSet<B_UsernameList> B_UsernameList { get; set; }
        public virtual DbSet<S_DepartmenttypeList> S_DepartmenttypeList { get; set; }
        public virtual DbSet<S_DiseaseList> S_DiseaseList { get; set; }
        public virtual DbSet<S_JournalList> S_JournalList { get; set; }
        public virtual DbSet<S_SickpersonRajectoryrList> S_SickpersonRajectoryrList { get; set; }
        public virtual DbSet<S_UrlList> S_UrlList { get; set; }
        public virtual DbSet<S_UserroleList> S_UserroleList { get; set; }
    }
}
