//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicGeographicInformationProscenium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_JournalList
    {
        public int JournalID { get; set; }
        public Nullable<int> usernameID { get; set; }
        public string Operate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
    }
}
